traffic_index/output/list_of_countries.csv, traffic_index/traffic_index/items.py, traffic_index/traffic_index/settings.py, traffic_index/traffic_index/spiders/__init__.py, traffic_index/traffic_index/spiders/traffic.py
=> feat: Feature/scrape traffic index

README.md
Hey, 
I've just rephrased the description of the project in README.md. 
Please, take a look.
=> fix: Description in README.md

.gitignore
#12 is resolved. Please, check.
=> chore: gitignore by removing commented lines

where.py
=> fix: case problem :bug:

.pre-commit-config.yaml, where.py
=> Add mypy and fix where.py

where.py
Closes:#50
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii73/place2live/55)
=> feat: Sort dataframe by fredomhouse_score 

where.py
Closes:#47
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii73/place2live/56)
=> Solve userwarning

where.py
close #58
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii73/place2live/60)
=> Replace capitalize on title

.travis.yml
I'm not sure, that i did all right, but i added travisbuddy in .travis.yml
close #61
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii73/place2live/65)
=> Add travisbuddy code in .travis.yml

city/city/__init__.py, city/city/items.py, city/city/middlewares.py, city/city/pipelines.py, city/city/settings.py, city/city/spiders/__init__.py, city/city/spiders/lists_of_cities.py, traffic_index/traffic_index/items.py, traffic_index/traffic_index/middlewares.py, traffic_index/traffic_index/pipelines.py, traffic_index/traffic_index/settings.py, traffic_index/traffic_index/spiders/__init__.py, traffic_index/traffic_index/spiders/traffic.py, where.py
Remove coding string
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii73/place2live/64)
=> Remove code string

.github/weekly-digest.yml
https://github.com/probot/weekly-digest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii73/place2live/68)
=> Add weekly-digest bot to the project

.github/topissuebot.yml
https://probot.github.io/apps/topissues/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii73/place2live/70)
=> Add topissuebot config

where.py
I have made formatting changes, adding functions to make the whole program more legible. I believe I have fixed the TypeErrors and ValueErrors. Maybe add a quit option to the program?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii73/place2live/82)
=> Exception Handling Added

README.md
Let me know what you think.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii73/place2live/91)
=> README.md installation updates

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii73/place2live/94)
=> Added to Readme.md

.github/auto-comment.yml
Close #69
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii73/place2live/95)
=> Add auto-comment bot

.pre-commit-config.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii73/place2live/101)
=> Change flake8 max-line-length to 120

world_universities_ranking/university_rankings.csv, world_universities_ranking/university_rankings.py
fix #31
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii73/place2live/105)
=> add world university rankings

where.py
Close #103
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii73/place2live/104)
=> "fix: Remove `text_type.ANSWER` from `There is no country better than {your country}.`

world_justice_project/world_justice.csv, world_justice_project/world_justice_scraper.py
fix #81 
That will scrape for each country the following data:
- name
- region
- overall_score
- overall_rank
- income_rank
- region_rank
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii73/place2live/112)
=> add world justice project

countries-tax-rates/tax_rates.csv, countries-tax-rates/tax_rates_scraper.py
fix #17
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii73/place2live/118)
=> add countries tax rates

corruption_perception_index/corruption_index.csv, corruption_perception_index/corruption_index_scraper.py
fix #13 
This will scrape the following information:
1. country name
2. region
3. rank/180
4. score/100
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii73/place2live/117)
=> add corruption perception index

country_data_grabber/country_data_grabber.py, world_justice_project/world_justice_scraper.py
This pull request Closes #110
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii73/place2live/119)
=> Grab data of a given country

inflation/inflation/items.py, inflation/inflation/middlewares.py, inflation/inflation/pipelines.py, inflation/inflation/settings.py, inflation/inflation/spiders/__init__.py, inflation/inflation/spiders/inflation.py
Close #18
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii73/place2live/97)
=> Adds inflation crawl

intentional_homicide_rate/intentional_homicide_rate.csv, intentional_homicide_rate/wiki.py
Close #14
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii73/place2live/98)
=> Completed Scrapy Spider and Crawled Wiki Page

query_a_country.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii73/place2live/115)
=> added query_a_country #110

CONTRIBUTING.md, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/place2live/place2live/145)
=> Add instruction to reorder imports 

where.py
Completed adding the notes column to the dataframe and build it with a note about the displacement crises. I have two things to note. 
1. CAR (Central African Republic) was not in the original df, so I did not include it in the displacement dictionary.
2. I wasn't sure how this is meant to be used in the main function, so I just built the displacement_col function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/place2live/place2live/152)
=> Complete issue #6 (displacement crises)

where.py
Addresses the issue #142
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/place2live/place2live/143)
=> Add tooltip

.pre-commit-config.yaml, README.md, inflation/inflation/items.py, inflation/inflation/spiders/inflation.py, scraper/scraper/items.py, traffic_index/traffic_index/items.py, where.py
Also fix style issues to pass `pre-commit` and remove Black badge. See https://github.com/place2live/place2live/issues/48#issuecomment-546264057.
=> Use isort instead of reorder-python-imports

where.py
Solves issue #158: just added a cached method to retrieve the value from the dbm - if the key is present - or from the url - and store it in the dbm for a next hit.
=> Adds dbm to where.py

scraper/scraper/spiders/traffic.py
=> Update traffic.py docs

where.py
Hi @serhii73 ,
This is my initial working version of the requirement. Added the universities info (topmost university in country) along with it's ranking to where.py. Please review this change.
=> Adding universities and university ranking info to where.py
